#!/bin/bash
cd
if [ $(id -u) != 0 ]
then
echo "Ejecute el script como root"
exit
fi
echo -e "\033[1;30mInstalando...\033[0m"
mkdir /etc/VpsPackdir 2>/dev/null
mkdir /etc/VpsPackdir/limite 2>/dev/null
mkdir /etc/VpsPackdir/senha 2>/dev/null
rm -rf /bin/limite 2>/dev/null
wget -o /dev/null -O- https://raw.githubusercontent.com/angelbanderasl/VpsPack/master/limite > /bin/limite
chmod +x /bin/limite
rm -rf /bin/criarusuario 2>/dev/null
wget -o /dev/null -O- https://raw.githubusercontent.com/angelbanderasl/VpsPack/master/criarusuario > /bin/criarusuario
chmod +x /bin/criarusuario
rm -rf /bin/deletarusuario 2>/dev/null
wget -o /dev/null -O- https://raw.githubusercontent.com/angelbanderasl/VpsPack/master/deletarusuario > /bin/deletarusuario
chmod +x /bin/deletarusuario
rm -rf /bin/redefinirusuario 2>/dev/null
wget -o /dev/null -O- https://raw.githubusercontent.com/angelbanderasl/VpsPack/master/redefinirusuario > /bin/redefinirusuario
chmod +x /bin/redefinirusuario
rm -rf /bin/vpspack 2>/dev/null
wget -o /dev/null -O- https://raw.githubusercontent.com/angelbanderasl/VpsPack/master/vpspack > /bin/vpspack
chmod +x /bin/vpspack
rm -rf /bin/speedtest.py 2>/dev/null
wget -o /dev/null -O- https://raw.githubusercontent.com/angelbanderasl/VpsPack/master/speedtest.py > /bin/speedtest.py
chmod +x /bin/speedtest.py
rm -rf dropbear 2>/dev/null
wget -o /dev/null -O- https://raw.githubusercontent.com/angelbanderasl/VpsPack/master/dropbear > dropbear
chmod +x dropbear
clear
echo -e "\033[1;32mInstalacion Finalizada\n\033[1;30mEjecute:"
echo -e "\n\033[1;32mvpspack \033[1;30mMenu de opciones"
echo -e "\033[1;32mOpcion 3 \033[1;30mCrear un usuario con fecha y limite"
echo -e "\033[1;32mOpcion 12 \033[1;30mBorrar un usuario o desconectarlo"
echo -e "\033[1;32mOpcion 11 \033[1;30mCambiar contraseña, fecha o limite"
echo -e "\033[1;32mModificada por: \033[1;30mAngel Banderas"
echo -e "\033[1;32mInstalada \033[1;30mVersion 2.1\033[0m"
rm -rf install
