#!/bin/bash
echo -e "\033[1;33mHosts\033[1;30m
1) Añadir hosts
2) Eliminar hosts"
read -p "opcion: " option
if [ $option -eq 1 ]; then
addhost
exit 0
fi

if [ $option -eq 2 ]; then
removerhost
exit
fi
