#!/bin/bash
read -p "Nombre del usuario: " namer
 if cat /etc/passwd |grep $namer: > /dev/null
 then
 echo " "
 else
 clear
 echo "El usuario $namer no existe"
 exit
 fi
clear
echo -e "\033[1;33mSeleccione una Opcion\033[1;30m
echo -e "\033[1;32m 1) Numero de Conexiones\033[1;30m
echo -e "\033[1;32m 2) Fecha de expiracion\033[1;30m
echo -e "\033[1;32m 3) Cambiar contraseña del usuario"\033[1;30m
read -p "opcion: " option
if [ $option -eq 1 ]; then
read -p "Cual es el nuevo limite de logins: " liml
limite $namer $liml
exit 0
fi

if [ $option -eq 2 ]; then
echo "Cual es la nueva fecha : formato AAAA/MM/DD"
read -p ": " date
chage -E $date $namer 2> /dev/null
echo -e "\033[1;31mEl usuario $namer se desconectara el dia: $date\033[0m"
exit
fi
if [ $option -eq 3 ]
then
read -p "Cual es la nueva contraseña para el usuario $namer: " senha
(echo "$senha" ; echo "$senha" ) |passwd $namer > /dev/null 2>/dev/null
echo "$senha" > /etc/VpsPackdir/senha/$namer
echo "Nueva contraseña aplicada: $senha"
exit
fi
